[package]
name = "rustpro"
version = "0.1.0"
authors = ["Anwaarahmedshah <fa15be0011@maju.edu.pk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
